name: Static Code Analysis

on:
    - pull_request
    - push

permissions:
    contents: read # to fetch code (actions/checkout)

concurrency:
    group: sca-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
    cancel-in-progress: true

    tests:
        strategy:
            fail-fast: false

        name: Static Code Analysis

        runs-on: ubuntu-20.04

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP with Composer deps
              uses: ./.github/composite-actions/setup-php-with-composer-deps
              with:
                  os: ${{ runner.os }}
                  php: 7.4

            - name: PHP CS Fixer
              run: composer run cs:check
